- name: install ssh authorized keys
  template: src=ssh_authorized_keys dest=/root/.ssh/authorized_keys mode=0600

- name: enable ipv4 forwarding for docker's communication
  shell: sysctl net.ipv4.conf.all.forwarding=1
